# Generated by Django 6.1 on 2026-08-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_event_image_square_event_square_source'),
        ('intake', '0004_association_home_description_association_home_title'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='one_booking_per_member',
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_on',
            field=models.DateField(blank=True, help_text='The day they turned up and paid the fee.', null=True, verbose_name='confirmed on'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='contact email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='booking',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='fee paid'),
        ),
        migrations.AddField(
            model_name='booking',
            name='fee_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Bank transfer'), ('other', 'Other')], max_length=10, verbose_name='paid by'),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='intake.submission', verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Filled in when the booking is confirmed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='members.member', verbose_name='member'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('event', 'member'), name='one_booking_per_member'),
        ),
    ]
