# Generated by Django 6.1 on 2026-08-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_checkin_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Not shown to the public yet.', max_digits=7, null=True, verbose_name='suggested cost'),
        ),
    ]
