# Generated by Django 6.1 on 2026-08-18 08:02

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("street", models.CharField(max_length=200, verbose_name="street")),
                ("postcode", models.CharField(max_length=5, verbose_name="postcode")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("tax_code", models.CharField(max_length=16, verbose_name="tax code")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "statute_url",
                    models.URLField(blank=True, verbose_name="statute link"),
                ),
                (
                    "membership_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="annual membership fee",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="associations/", verbose_name="logo"
                    ),
                ),
                (
                    "colour_primary",
                    models.CharField(
                        default="#ED5C08",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$",
                                "Use a six-digit hex colour, for example #ED5C08",
                            )
                        ],
                        verbose_name="primary colour",
                    ),
                ),
                (
                    "colour_accent",
                    models.CharField(
                        default="#528116",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$",
                                "Use a six-digit hex colour, for example #ED5C08",
                            )
                        ],
                        verbose_name="accent colour",
                    ),
                ),
                (
                    "colour_neutral",
                    models.CharField(
                        default="#4C5057",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$",
                                "Use a six-digit hex colour, for example #ED5C08",
                            )
                        ],
                        verbose_name="neutral colour",
                    ),
                ),
            ],
            options={
                "verbose_name": "association",
                "verbose_name_plural": "associations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PublicForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("intro", models.TextField(blank=True, verbose_name="introduction")),
                ("is_open", models.BooleanField(default=True, verbose_name="open")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="intake.association",
                        verbose_name="association",
                    ),
                ),
            ],
            options={
                "verbose_name": "public form",
                "verbose_name_plural": "public forms",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=10,
                        verbose_name="state",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("self", "For myself"),
                            ("minor", "For a minor child"),
                            ("protected", "For a person I am the legal guardian of"),
                        ],
                        max_length=10,
                        verbose_name="applying for",
                    ),
                ),
                (
                    "applicant_first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="first name"
                    ),
                ),
                (
                    "applicant_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="last name"
                    ),
                ),
                (
                    "applicant_birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "applicant_birth_place",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="place of birth"
                    ),
                ),
                (
                    "applicant_tax_code",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="tax code"
                    ),
                ),
                (
                    "applicant_street",
                    models.CharField(blank=True, max_length=200, verbose_name="street"),
                ),
                (
                    "applicant_number",
                    models.CharField(blank=True, max_length=10, verbose_name="number"),
                ),
                (
                    "applicant_postcode",
                    models.CharField(blank=True, max_length=5, verbose_name="postcode"),
                ),
                (
                    "applicant_city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "applicant_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "applicant_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "member_first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="first name"
                    ),
                ),
                (
                    "member_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="last name"
                    ),
                ),
                (
                    "member_birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "member_birth_place",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="place of birth"
                    ),
                ),
                (
                    "member_tax_code",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="tax code"
                    ),
                ),
                (
                    "member_street",
                    models.CharField(blank=True, max_length=200, verbose_name="street"),
                ),
                (
                    "member_number",
                    models.CharField(blank=True, max_length=10, verbose_name="number"),
                ),
                (
                    "member_city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "accepts_statute",
                    models.BooleanField(
                        default=False, verbose_name="accepts the statute"
                    ),
                ),
                (
                    "sole_holder",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="sole holder of parental responsibility",
                    ),
                ),
                (
                    "second_parent_first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="first name"
                    ),
                ),
                (
                    "second_parent_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="last name"
                    ),
                ),
                (
                    "second_parent_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "consent_images",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="image consent"
                    ),
                ),
                (
                    "consent_whatsapp",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="WhatsApp consent"
                    ),
                ),
                (
                    "place",
                    models.CharField(blank=True, max_length=100, verbose_name="place"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="intake.publicform",
                        verbose_name="form",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission",
                "verbose_name_plural": "submissions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signatory_name",
                    models.CharField(max_length=200, verbose_name="signatory"),
                ),
                (
                    "signatory_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Applicant"),
                            (
                                "second_parent",
                                "Second holder of parental responsibility",
                            ),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("membership", "Membership application"),
                            ("image_consent", "Image consent"),
                        ],
                        max_length=20,
                        verbose_name="subject",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting signature"),
                            ("signed", "Signed"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="state",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "declaration",
                    models.TextField(blank=True, verbose_name="declaration"),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="signed at"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="intake.submission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "ordering": ("submission", "role"),
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("subject", "Who the application is for"),
                            ("applicant", "Who is applying"),
                            ("member", "Member details"),
                            ("statute", "Statute and fee"),
                            ("privacy", "Privacy notice"),
                            ("consents", "Image consents"),
                            ("review", "Review and subscription"),
                        ],
                        max_length=20,
                        verbose_name="section",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="enabled"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="intake.publicform",
                        verbose_name="form",
                    ),
                ),
            ],
            options={
                "verbose_name": "section",
                "verbose_name_plural": "sections",
                "ordering": ("order",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("form", "key"), name="unique_section_key"
                    )
                ],
            },
        ),
    ]
