# Generated by Django 6.1 on 2026-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="reminded at"
            ),
        ),
    ]
