# Generated by Django 6.1 on 2026-08-18 18:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_submission_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='home_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='home page description'),
        ),
        migrations.AddField(
            model_name='association',
            name='home_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='home page title'),
        ),
    ]
