# Generated by Django 6.1 on 2026-08-22 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intake", "0004_association_home_description_association_home_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="association",
            options={
                "ordering": ("name",),
                "verbose_name": "association",
                "verbose_name_plural": "association",
            },
        ),
    ]
