# Generated by Django 6.1 on 2026-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_seed_default_age_brackets'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='applicant_province',
            field=models.CharField(blank=True, max_length=2, verbose_name='province'),
        ),
        migrations.AddField(
            model_name='submission',
            name='member_province',
            field=models.CharField(blank=True, max_length=2, verbose_name='province'),
        ),
    ]
