# Generated by Django 6.1 on 2026-08-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0009_submission_applicant_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='default_location',
            field=models.CharField(blank=True, help_text='Pre-fills the location field when an editor creates an event.', max_length=200, verbose_name='default event location'),
        ),
        migrations.AddField(
            model_name='publicform',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Preselected when an editor creates an event. Only one per association: marking this one unmarks any other.', verbose_name='default'),
        ),
    ]
